version: '3'
services:

  postgresql-db:
    container_name: postgresql-db
    image: postgres:11-alpine
    hostname: ${POSTGRESQL_DB_HOST}
    ports:
      - "${POSTGRESQL_DB_EXTERNAL_PORT}:${POSTGRESQL_DB_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRESQL_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_DB_USERNAME}'" ]
      timeout: 45s
      interval: 10s
      retries: 2
    restart: always
    volumes:
      - "./db-init:/docker-entrypoint-initdb.d"
      - "postgres_data:${POSTGRESQL_DB_DATA_PATH}"
      - "postgres_backup:${POSTGRESQL_DB_BACKUP}"
    env_file: .env

volumes:
  postgres_data:
  postgres_backup: