spring:
  application:
    name: config-service
  profiles:
    active: ${APP_PROFILE}
  security:
    user:
      name: ${CONFIG_SERVER_SECURITY_USERNAME}
      password: ${CONFIG_SERVER_SECURITY_PASSWORD}
      roles: ${CONFIG_SERVER_SECURITY_ROLE}
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_SERVER_GIT_URI_BRANCH}
          uri: ${CONFIG_SERVER_GIT_URI}
          username: ${CONFIG_SERVER_GIT_URI_USERNAME}
          password: ${CONFIG_SERVER_GIT_URI_PASSWORD}

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 20
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_SECURITY_USERNAME}:${DISCOVERY_SERVER_SECURITY_PASSWORD}@${APP_HOST}:${DISCOVERY_SERVER_PORT}/${APP_CONTEXT_PATH}/eureka/

server:
  port: ${CONFIG_SERVER_PORT}
  servlet:
    context-path: /${APP_CONTEXT_PATH}